export const customers = [
  {
  'ID': 1,
  'Customer': 'Colin Pear',
  'Food': 'Pizza',
  'Color': 'Blue',
  'Animal': 'Koala',
  'Car': 'Mustang',
  'Location': 'USA',
  },
  {
  'ID': 2,
  'Customer': 'Colin Pear',
  'Food': 'Pizza',
  'Color': 'Blue',
  'Animal': 'Koala',
  'Car': 'Mustang',
  'Location': 'USA',
  },
  {
  'ID': 3,
  'Customer': 'Colin Pear',
  'Food': 'Pizza',
  'Color': 'Blue',
  'Animal': 'Koala',
  'Car': 'Mustang',
  'Location': 'USA',
  },
  {
  'ID': 4,
  'Customer': 'Colin Pear',
  'Food': 'Pizza',
  'Color': 'Blue',
  'Animal': 'Koala',
  'Car': 'Mustang',
  'Location': 'USA',
  },
  {
  'ID': 5,    
  'Customer': 'Colin Pear',
  'Food': 'Pizza',
  'Color': 'Blue',
  'Animal': 'Koala',
  'Car': 'Mustang',
  'Location': 'USA',
  },
  {
  'ID': 6,
  'Customer': 'Colin Pear',
  'Food': 'Pizza',
  'Color': 'Blue',
  'Animal': 'Koala',
  'Car': 'Mustang',
  'Location': 'USA',
  },
  {
  'ID': 7,
  'Customer': 'Colin Pear',
  'Food': 'Pizza',
  'Color': 'Blue',
  'Animal': 'Koala',
  'Car': 'Mustang',
  'Location': 'USA',
  }
]